### ISSUE TITLE
Please point out the difference between r-ROME and ROME

### ISSUE THREAD

**Issue by Luoyang144** [scalable-model-editing/rebuilding-rome#1]
Thank you for your work. When can you post the difference between r-ROME and ROME? When I was looking through the code, I saw that MEMIT related functions were used in r-ROME. Is this the main reason why model editing did not crash?

**Comment by akshat57** [comment]
Yes that is quite likely. We built the code-base on MEMIT and re-implemented the ROME equations within it. It was quite surprising to us that just that change fixed the problem of model collapse.

**Comment by akshat57** [comment]
Hi, 

We have updated our code to highlight the exact discrepancies in the original ROME code that lead to disabling edits. We have also updated our paper to point the exact differences mathematically that lead to disabling edits - https://arxiv.org/abs/2403.07175

**Comment by Luoyang144** [comment]
Thanks for reply!
Marvelous job, looking forward to your future research.🙌
